# Generated by Django 4.1.6 on 2023-02-02 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_post_product_views"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.RemoveField(
            model_name="product",
            name="views",
        ),
    ]
